name: Build and Send APK to Telegram

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Decode Keystore
        run: |
          echo "$SIGNING_KEYSTORE" | base64 --decode > my-release-key.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        env:
          SIGNING_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Send APK to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID_1: ${{ secrets.TELEGRAM_CHAT_ID_1 }}
          CHAT_ID_2: ${{ secrets.TELEGRAM_CHAT_ID_2 }}
        run: |
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          curl -F chat_id=$CHAT_ID_1 -F document=@"$APK_PATH" "https://api.telegram.org/bot$BOT_TOKEN/sendDocument"
          curl -F chat_id=$CHAT_ID_2 -F document=@"$APK_PATH" "https://api.telegram.org/bot$BOT_TOKEN/sendDocument"