name: Test Keystore

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: |
          echo "=== SECRETS DEBUG ==="
          echo "SIGNING_KEY_ALIAS length: ${#SIGNING_KEY_ALIAS}"
          echo "SIGNING_KEY_ALIAS value: '$SIGNING_KEY_ALIAS'"
          echo "SIGNING_KEY_PASSWORD length: ${#SIGNING_KEY_PASSWORD}"
          echo "SIGNING_STORE_PASSWORD length: ${#SIGNING_STORE_PASSWORD}"
          echo "SIGNING_KEYSTORE length: ${#SIGNING_KEYSTORE}"
          echo "=== END SECRETS DEBUG ==="
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE }}

      - name: Decode Keystore
        run: |
          echo "=== KEYSTORE TEST DEBUG ==="
          echo "Current directory: $(pwd)"
          echo "Directory contents before decoding:"
          ls -la
          echo "Testing keystore decoding to app/ folder..."
          echo "$SIGNING_KEYSTORE" | base64 --decode > app/release-keystore.jks
          echo "Keystore decoded to: app/release-keystore.jks"
          echo "Directory contents after decoding:"
          ls -la
          echo "App folder contents:"
          ls -la app/
          echo "File size: $(wc -c < app/release-keystore.jks) bytes"
          echo "Keystore file exists: $(test -f app/release-keystore.jks && echo "YES" || echo "NO")"
          echo "=== END KEYSTORE TEST DEBUG ==="
        env:
          SIGNING_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE }}

      - name: Test Gradle Properties
        run: |
          echo "=== GRADLE PROPERTIES TEST ==="
          echo "Testing Gradle properties..."
          
          # Устанавливаем переменные окружения
          export RELEASE_KEYSTORE_PATH="release-keystore.jks"
          export SIGNING_KEY_ALIAS="${{ secrets.SIGNING_KEY_ALIAS }}"
          export SIGNING_KEY_PASSWORD="${{ secrets.SIGNING_KEY_PASSWORD }}"
          export SIGNING_STORE_PASSWORD="${{ secrets.SIGNING_STORE_PASSWORD }}"
          
          echo "Environment variables:"
          echo "RELEASE_KEYSTORE_PATH: '$RELEASE_KEYSTORE_PATH'"
          echo "SIGNING_KEY_ALIAS: '$SIGNING_KEY_ALIAS'"
          echo "SIGNING_KEY_PASSWORD: [HIDDEN]"
          echo "SIGNING_STORE_PASSWORD: [HIDDEN]"
          
          echo "File check:"
          echo "Keystore exists: $(test -f app/$RELEASE_KEYSTORE_PATH && echo "YES" || echo "NO")"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "App folder contents:"
          ls -la app/
          
          echo "=== KEYSTORE CONTENTS TEST ==="
          echo "Checking keystore contents..."
          if command -v keytool &> /dev/null; then
            echo "Keytool found, listing keystore contents:"
            echo "Using keystore path: app/$RELEASE_KEYSTORE_PATH"
            keytool -list -keystore "app/$RELEASE_KEYSTORE_PATH" -storepass "$SIGNING_STORE_PASSWORD" 2>/dev/null || echo "Failed to list keystore contents"
          else
            echo "Keytool not found, cannot check keystore contents"
          fi
          
          echo "=== END GRADLE PROPERTIES TEST ==="
