name: Test Keystore

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode Keystore
        run: |
          echo "=== KEYSTORE TEST DEBUG ==="
          echo "Current directory: $(pwd)"
          echo "Directory contents before decoding:"
          ls -la
          echo "Testing keystore decoding..."
          echo "$SIGNING_KEYSTORE" | base64 --decode > release-keystore.jks
          echo "Keystore decoded to: release-keystore.jks"
          echo "Directory contents after decoding:"
          ls -la
          echo "File size: $(wc -c < release-keystore.jks) bytes"
          echo "Keystore file exists: $(test -f release-keystore.jks && echo "YES" || echo "NO")"
          echo "=== END KEYSTORE TEST DEBUG ==="
        env:
          SIGNING_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE }}

      - name: Test Gradle Properties
        run: |
          echo "=== GRADLE PROPERTIES TEST ==="
          echo "Testing Gradle properties..."
          echo "RELEASE_KEYSTORE_PATH=release-keystore.jks" >> $GITHUB_ENV
          echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "SIGNING_STORE_PASSWORD=${{ secrets.SIGNING_STORE_PASSWORD }}" >> $GITHUB_ENV
          
          echo "Environment variables:"
          echo "RELEASE_KEYSTORE_PATH: $RELEASE_KEYSTORE_PATH"
          echo "SIGNING_KEY_ALIAS: $SIGNING_KEY_ALIAS"
          echo "SIGNING_KEY_PASSWORD: [HIDDEN]"
          echo "SIGNING_STORE_PASSWORD: [HIDDEN]"
          
          echo "File check:"
          echo "Keystore exists: $(test -f $RELEASE_KEYSTORE_PATH && echo "YES" || echo "NO")"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "=== END GRADLE PROPERTIES TEST ==="
