name: Test Keystore

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode Keystore
        run: |
          echo "Testing keystore decoding..."
          echo "$SIGNING_KEYSTORE" | base64 --decode > release-keystore.jks
          echo "Keystore decoded to: release-keystore.jks"
          ls -la
          echo "File size: $(wc -c < release-keystore.jks) bytes"
        env:
          SIGNING_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE }}

      - name: Test Gradle Properties
        run: |
          echo "Testing Gradle properties..."
          echo "RELEASE_KEYSTORE_PATH=release-keystore.jks" >> $GITHUB_ENV
          echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "SIGNING_STORE_PASSWORD=${{ secrets.SIGNING_STORE_PASSWORD }}" >> $GITHUB_ENV
          
          echo "Environment variables:"
          echo "RELEASE_KEYSTORE_PATH: $RELEASE_KEYSTORE_PATH"
          echo "SIGNING_KEY_ALIAS: $SIGNING_KEY_ALIAS"
          echo "SIGNING_KEY_PASSWORD: [HIDDEN]"
          echo "SIGNING_STORE_PASSWORD: [HIDDEN]"
